### ISSUE TITLE
文中的博客地址链接失效

### ISSUE THREAD

**Issue by binc4t** [BEWINDOWEB/lotterygrabber#2]
大佬你文中的博客地址该更新了

**Comment by BEWINDOWEB** [comment]
感谢关注。
很久以前写的玩具项目了，看了下，原博客文章也只是简单的贴爬取代码而已，没啥意义，我直接把readme中相关部分删掉了。
后面会考虑删除这个项目，如果感兴趣可以fork到自己仓库 :)
